spring.application.name=single-user-security-demo
spring.main.banner-mode=off

# Single User
spring.security.user.username=user
spring.security.user.password=user123
spring.security.user.role=ADMIN

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false